FROM metno/pycsw:2.4.2
LABEL purpose="Development of the S-ENDA CSW catalog service"
ENV PYTHONUNBUFFERED=1

USER root
# Install dependencies
RUN pip install \
    coverage \
    ipdb

WORKDIR /home/pycsw
USER pycsw
