# Usage: docker-compose -f docker-compose.yml -f docker-compose.test.yml build
---
version: '3.4' # minimum docker-compose file format version

services:
  #
  # catalog-service-api (pycsw)
  #

  catalog-service-api:
    build:
      context: ./catalog-service-api
      dockerfile: ${DOCKERFILE:-Dockerfile}

