---
version: '3.4' # minimum docker-compose file format version

x-restart:
  &default-restart-policy
  unless-stopped

x-logging:
  &default-logging-policy
    driver: journald

networks:
  internal:

services:
  postgis:
    image: postgis/postgis:13-master
    networks:
      internal:
        aliases:
          - postgis
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: csw_db
    volumes:
      - /srv/postgis:/var/lib/postgresql/data

  #
  # catalog-service-api (pycsw)
  #

  catalog-service-api:
    image: docker.io/metno/senda-csw-catalog-service:${VERSION:-dev}-catalog-service-api
    build:
      context: ./catalog-service-api
      dockerfile: ${DOCKERFILE:-Dockerfile.staging}
    ports:
      - "80:8000"
    networks:
      internal:
    environment:
      INDEXDB: "true"
      ISO_STORE: "/isostore"
    volumes:
      - ./lib/isostore:/isostore:ro
    logging: *default-logging-policy
    restart: *default-restart-policy
    depends_on:
      - postgis

  #
  # iso-converter
  #

  iso-converter:
    image: docker.io/metno/senda-csw-catalog-service:${VERSION:-dev}-iso-converter
