---
version: '3.4' # minimum docker-compose file format version

x-restart:
  &default-restart-policy
  unless-stopped

x-logging:
  &default-logging-policy
    driver: journald

services:
  #
  # catalog-service-api (pycsw)
  #

  catalog-service-api:
    image: docker.io/metno/senda-prototype:${VERSION:-dev}-catalog-service-api
    ports:
      - "80:8000"
    environment:
      INDEXDB: "true"
      ISO_STORE: "/isostore"
    volumes:
      - ./isostore:/isostore:ro
    logging: *default-logging-policy
    restart: *default-restart-policy

  #
  # iso-converter
  #

  iso-converter:
    image: docker.io/metno/senda-prototype:${VERSION:-dev}-iso-converter
