# Usage: docker-compose -f docker-compose.yml -f docker-compose.build.yml build
---
version: '3.4' # minimum docker-compose file format version

services:
  #
  # catalog-service-api (pycsw)
  #

  catalog-service-api:
    build:
      context: ./catalog-service-api

  #
  # iso-converter
  #

  iso-converter:
    build:
      context: ./iso-converter
